listen:
    address: 0.0.0.0
    port: 8080
token:
    api: 259128871:AAHrZhniOJc1x919OfRA6I3Mmz5rNhxVyaI
    webhook: VmsY3vzVXGTMXbCnRcwPUY7vNxCPAZmP
groups:
    -   name: æŸæ··èšçš„ Telegram æœºå™¨äººå®éªŒå®¤
        id: -1001076795424
        cooling_speed: 10
        threshold: 100
        emojis: ["ğŸ˜‚", "ğŸ˜‹"]
        max_repeat: 5
    -   name: ï½ç°ä»£å‰ç«¯é­”æ³•éƒ¨ï½
        id: -1001066867565
    -   name: "#archlinux-cn"
        id: -1001031857103
        emojis: ["ğŸ˜‚", "ğŸ˜‹", "ğŸŒš"]